# Generated by Django 2.0.5 on 2018-08-08 01:49

import datetime
from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(default='kathmandu', max_length=50, validators=[restaurants.validators.validate_city])),
                ('location', models.CharField(blank=True, max_length=50)),
                ('open_time', models.TimeField(blank=True, default=datetime.time(9, 0))),
                ('close_time', models.TimeField(blank=True, default=datetime.time(18, 0))),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
