# Generated by Django 2.0 on 2017-12-10 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(default='Kathmandu', max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('open_time', models.TimeField(default=datetime.time(9, 0))),
                ('close_time', models.TimeField(default=datetime.time(18, 0))),
            ],
        ),
    ]
