# Generated by Django 2.0 on 2017-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.CharField(auto_created=True, max_length=50, unique=True),
        ),
    ]
