# Generated by Django 2.0 on 2017-12-11 18:40

import datetime
from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='kathmandu', max_length=50, validators=[restaurants.validators.validate_city]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
    ]
