# Generated by Django 2.0.5 on 2018-08-08 01:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveSmallIntegerField()),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_parking', models.CharField(choices=[(0, 'NO'), (1, 'YES')], default='YES', max_length=50)),
                ('car_parking', models.CharField(choices=[(0, 'NO'), (1, 'YES')], default='NO', max_length=50)),
                ('smoking', models.CharField(choices=[(0, 'NO'), (1, 'YES')], default='NO', max_length=50)),
                ('vat', models.CharField(choices=[(0, 'NO'), (1, 'ANY')], default='ANY', max_length=50)),
                ('prange', models.CharField(choices=[(0, 'ANY'), (1, 'LOW'), (2, 'MID'), (3, 'HIGH')], default=0, max_length=50)),
                ('delivery', models.CharField(choices=[(0, 'NO'), (1, 'YES')], default='NO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RateReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment_head', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('bike_parking', models.CharField(blank=True, choices=[(0, 'NO'), (1, 'YES')], max_length=10)),
                ('car_parking', models.CharField(blank=True, choices=[(0, 'NO'), (1, 'YES')], max_length=10)),
                ('smoking', models.CharField(blank=True, choices=[(0, 'NO'), (1, 'YES')], max_length=10)),
                ('vat', models.CharField(blank=True, choices=[(0, 'NO'), (1, 'ANY')], max_length=10)),
                ('prange', models.CharField(blank=True, choices=[(0, 'ANY'), (1, 'LOW'), (2, 'MID'), (3, 'HIGH')], max_length=10)),
                ('delivery', models.CharField(blank=True, choices=[(0, 'NO'), (1, 'YES')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='ratereview',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restu', to='foodapp.Restaurant'),
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use', to='foodapp.User'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res', to='foodapp.Restaurant'),
        ),
    ]
