# Generated by Django 2.0.5 on 2018-08-07 02:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import foodapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_parking', models.CharField(default='NE', max_length=50, validators=[foodapp.models.validate_nyn])),
                ('car_parking', models.CharField(default='NE', max_length=50, validators=[foodapp.models.validate_nyn])),
                ('smoking', models.CharField(default='NE', max_length=50, validators=[foodapp.models.validate_nyn])),
                ('vat', models.CharField(default='NE', max_length=50, validators=[foodapp.models.validate_nyn])),
                ('prange', models.CharField(default='NE', max_length=50, validators=[foodapp.models.validate_nyn])),
                ('delivery', models.CharField(default='NE', max_length=50, validators=[foodapp.models.validate_nyn])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('bike_parking', models.CharField(default='NE', max_length=10, validators=[foodapp.models.validate_nyn])),
                ('car_parking', models.CharField(default='NE', max_length=10, validators=[foodapp.models.validate_nyn])),
                ('smoking', models.CharField(default='NE', max_length=10, validators=[foodapp.models.validate_nyn])),
                ('vat', models.CharField(default='NE', max_length=10, validators=[foodapp.models.validate_nyn])),
                ('prange', models.CharField(default='NE', max_length=10, validators=[foodapp.models.validate_nyn])),
                ('delivery', models.CharField(default='NE', max_length=10, validators=[foodapp.models.validate_nyn])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use', to='foodapp.User'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res', to='foodapp.Restaurant'),
        ),
    ]
