# Generated by Django 2.0.5 on 2018-08-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='prange',
            field=models.CharField(choices=[(0, 'ANY'), (1, 'LOW'), (2, 'MID'), (3, 'HIGH')], default='ANY', max_length=50),
        ),
    ]
