# Generated by Django 2.0.5 on 2018-08-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20180808_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratereview',
            old_name='comment_head',
            new_name='comment',
        ),
    ]
