# Generated by Django 2.0.5 on 2018-08-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20180809_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratereview',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
