# Generated by Django 2.0.5 on 2018-08-09 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_ratereview_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratereview',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restua', to='foodapp.Restaurant'),
        ),
    ]
