# Generated by Django 2.0 on 2017-12-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20171212_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated',
        ),
    ]
